apiVersion: dbaas.example.com/v1alpha1
kind: ClusterBackup
metadata:
  labels:
    app.kubernetes.io/name: db-operator
    app.kubernetes.io/managed-by: kustomize
  name: clusterbackup-sample
spec:
  # TODO(user): Add fields here
