## Append samples of your project ##
resources:
- everest_v1alpha1_cluster.yaml
- ops.example.com_v1alpha1_opsrequest.yaml
- dbaas_v1alpha1_clusterbackup.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
