apiVersion: ops.example.com.example.com/v1alpha1
kind: OpsRequest
metadata:
  labels:
    app.kubernetes.io/name: db-operator
    app.kubernetes.io/managed-by: kustomize
  name: opsrequest-sample
spec:
  # TODO(user): Add fields here
